service: new-service-name

custom:
  sample_env: sample_env
  stage: dev
  runtime: python2.7
  region: eu-west-1

provider:
  name: aws
  runtime: ${self:custom.runtime}
  stage: ${opt:stage, self:custom.stage}
  region: ${env:AWS_REGION, self:custom.region}
  memorySize: ${file(../default.yml):memorySize}
  cfLogs: true
  environment:
    SAMPLE_ENV: ${self:custom.sample_env}


functions:
  read:
    handler: read.read
    events:
      - http:
          path: sample/path
          method: get
          cors: true
