service: new-service-name

provider:
  name: aws
  runtime: python2.7 #
  stage: dev
  region: eu-west-1
  memorySize: 128
  cfLogs: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "s3:ListBucket"
      Resource: "arn:aws:dynamodb:eu-west-1:*:*"
  environment:
    SAMPLE_ENV: sample_env


functions:
  read:
    handler: read.read
    events:
      - http:
          path: sample/path
          method: get
          cors: true
